### ISSUE TITLE
Compatibility with Timex TC2048

### ISSUE THREAD

**Issue by barszpaw** [mad3001/Multiply#2]
While using Dandantor with Multiply I noticed that Reading from SD does not working.
It show garbage  instead content of SD card. On ZX Spectrum it works but on TC2048 does not.

**Comment by mad3001** [comment]
Hi, this is not a problem with Dandanator v2 or Multiply. It is well known that there are some ZX Spectrum computers that include a Kempston interface such as the Timex TC2048 and the Inves Plus 48k. Dandanator v2 has a Kempston interface and Multiply uses this Kempston interface for its functions, if it is not able to communicate via that means no content comes out of the SD. The problem here is that these 2 Kempston interfaces conflict: Dandanator v2 and Timex TC2048. Multiply uses the Kempston interface of Dandanator so it can't communicate with ZX Spectrum because of this collision. The same happens if you connect a Kempston interface and Multiply to a ZX Spectrum 48 or 128k. The only solution for the Timex TC2048 would be to disable the internal Kempston interface, but logically that's not available to everyone and, at least, I wouldn't do it if you have another ZX Spectrum computer where you can use Multiply. For the Timex TC2048 it is best to use only the dandanator v2, without Multiply, and disabling its Joystick Kempston port.

**Comment by mad3001** [comment]
Thanks barszpaw for your comments on the issue. Although some people knew about this problem, it helped to add more information to the project.
If you are interested in how to disable TC2048 internal interface I can do some digging and check it on my TC2048 to provide you a solution for using Multiply with it. But the little I have seen would require desoldering and/or cutting pins on a chip.
